<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>关单核验台</AssemblyName>
    <RootNamespace>CustomsLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\CustomsClearanceConsole\Assets\app.ico</ApplicationIcon>
    <Version>1.3.0</Version>
    <FileVersion>1.3.0.0</FileVersion>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
