'use strict';
const paths={
folder:'<path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/><path d="M3 10h18"/>',
files:'<path d="M8 3h8l4 4v13H8Z"/><path d="M16 3v5h4M4 7v14M11 12h6M11 16h4"/>',
copy:'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M15 8V4H4v11h4"/>',
coins:'<ellipse cx="9" cy="6" rx="6" ry="3"/><path d="M3 6v5c0 2 3 3 6 3M3 11v5c0 2 3 3 6 3M15 6v3"/><ellipse cx="16" cy="12" rx="5" ry="3"/><path d="M11 12v6c0 2 2 3 5 3s5-1 5-3v-6"/>',
scan:'<path d="M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5M1 12h22M8 8h8M8 16h8"/>',
export:'<path d="M12 3v12m-4-4 4 4 4-4M4 15v6h16v-6M5 3h2M17 3h2"/>',
settings:'<path d="M4 6h16M4 12h16M4 18h16"/><rect x="7" y="4" width="4" height="4" rx="1" fill="currentColor" stroke="none"/><rect x="14" y="10" width="4" height="4" rx="1" fill="currentColor" stroke="none"/><rect x="7" y="16" width="4" height="4" rx="1" fill="currentColor" stroke="none"/>',
image:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="1.5"/><path d="m3 17 5-4 4 3 4-6 5 6"/>',
clean:'<path d="M4 6h16M9 3h6M6 6l1 15h10l1-15M10 10v7M14 10v7"/>',
'file-x':'<path d="M5 3h10l4 4v14H5ZM15 3v5h4M9 12l6 6M15 12l-6 6"/>',
list:'<path d="M4 5h16M4 10h16M4 15h7M4 20h7M15 15l6 6M21 15l-6 6"/>',
search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
chevron:'<path d="m6 9 6 6 6-6"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',
shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9S4 17 4 12V6Z"/><path d="m8 12 3 3 5-6"/>',
check:'<path d="m5 12 4 4L19 6"/>',
warning:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5M12 17v.5"/>',
external:'<path d="M14 3h7v7M21 3 10 14M10 3H3v18h18v-7"/>',
close:'<path d="m6 6 12 12M18 6 6 18"/>',
help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 1c0 2-3 2-3 4M12 17v.5"/>',
clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.files}</svg>`;
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const companies=['NORTHSTAR TRADING CO., LTD.','HARBOR INDUSTRIAL PTE. LTD.','MERIDIAN GLOBAL GmbH','EVERGREEN SUPPLY INC.','PACIFIC TECHNOLOGY LIMITED','SILVER OAK INTERNATIONAL','ATLAS INDUSTRIES CO., LTD.','NOVA COMMERCE PTE. LTD.'];
const demoRows=Array.from({length:20},(_,i)=>({id:i+1,no:'310120260908'+String(250701+i).padStart(6,'0'),company:companies[i%8],contract:`EX-2609-${String(1001+i).padStart(4,'0')}`,customs:i%3===0?'上海海关':'上海浦江',country:['美国','新加坡','德国','美国','英国'][i%5],currency:['CNY','USD','EUR'][i%3],amount:[346940,28460,18950,127800,64230,12850,268400,73500,9420,56000][i%10],duplicate:i<4,canonical:true,attention:i===2||i===6,saved:[0,1,4,5,9,14].includes(i),source:`出口关单_${250701+i}.pdf`}));
demoRows[1]={...demoRows[0],id:2,canonical:false,source:'出口关单_250701_副本.pdf'};
demoRows[3]={...demoRows[2],id:4,canonical:false,attention:false,source:'出口关单_250703_副本.pdf'};
demoRows[2].amount=18500;
let rows=structuredClone(demoRows),filter='all',page=1,pageSize=20,scanning=false,scanTimer=null,toastTimer=null,verificationRow=null,verifyTimeout=null,selected=new Set(),cleanupType='',cleanupStep=1,lastFocus=null;
function num(n){return n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function isNormal(r){return !r.duplicate&&!r.attention}
function getVisible(){return rows.filter(r=>(filter==='normal'?isNormal(r):filter==='duplicate'?r.duplicate:filter==='attention'?r.attention:true)&&r.no.includes($('#search').value.trim()))}
function render(){
 const visible=getVisible(),pages=Math.max(1,Math.ceil(visible.length/pageSize));page=Math.min(page,pages);const current=visible.slice((page-1)*pageSize,page*pageSize);selected.clear();$('#selection-hint').textContent='金额仅含已确认部分，需关注记录请先校对';document.querySelectorAll('[data-action="settings"]').forEach(b=>b.disabled=scanning);
 $('#file-count').textContent=rows.length;$('#duplicate-count').textContent=new Set(rows.filter(r=>r.duplicate).map(r=>r.no)).size;$('#duplicate-files').textContent=rows.filter(r=>r.duplicate).length;
 const currencies=[...new Set(rows.map(r=>r.currency))].sort();$('#money-rows').innerHTML=currencies.length?currencies.map(c=>`<div class="money-row"><span>${c}</span><span>${num(rows.filter(r=>r.currency===c).reduce((s,r)=>s+r.amount,0))}</span><span>${num(rows.filter(r=>r.currency===c&&r.canonical).reduce((s,r)=>s+r.amount,0))}</span></div>`).join(''):'<div class="money-row"><span>—</span><span>—</span><span>—</span></div>';
 $('#result-count').textContent=`${rows.length} 份文件`;$('#count-all').textContent=rows.length;$('#count-normal').textContent=rows.filter(isNormal).length;$('#count-duplicate').textContent=rows.filter(r=>r.duplicate).length;$('#count-attention').textContent=rows.filter(r=>r.attention).length;
 $('#rows').innerHTML=current.map((r,i)=>`<tr data-id="${r.id}" class="${r.duplicate?'duplicate':''}"><td tabindex="0">${String((page-1)*pageSize+i+1).padStart(2,'0')}</td><td tabindex="0" class="number" title="${r.no} · 源文件：${esc(r.source)}">${r.no}<span class="source">${esc(r.source)}</span></td><td tabindex="0" title="${esc(r.company)}"><span class="company">${esc(r.company)}</span></td><td tabindex="0" class="contract" title="${esc(r.contract)}">${esc(r.contract)}</td><td tabindex="0">${r.customs}</td><td tabindex="0">${r.country}</td><td tabindex="0" class="amount"><span class="currency">${r.currency}</span>${num(r.amount)}${r.attention?'<span class="source" style="color:var(--amber)">已确认部分</span>':''}</td><td tabindex="0"><div class="status-stack">${r.duplicate?`<span class="pill duplicate">${icon('copy')}重复单号</span>`:''}${r.attention?`<span class="pill attention">${icon('warning')}需关注</span>`:!r.duplicate?`<span class="pill normal">${icon('check')}识别完成</span>`:''}</div></td><td><div class="row-action">${r.saved?`<span class="saved" title="仅表示核验截图已保存，不代表海关放行">${icon('check')}已留存</span>`:''}<button class="verify-button" data-action="verify" data-id="${r.id}" ${scanning?'disabled':''} aria-label="核验关单 ${r.no}">${r.saved?'重核验':'核验'}${icon('external')}</button></div></td></tr>`).join('');
 $('#empty').hidden=current.length>0;$('#empty-title').textContent=rows.length?'没有找到匹配的关单':'从第一份关单开始';$('#empty-message').textContent=rows.length?'尝试更换单号关键词，或清除当前筛选条件。':'选择关单目录后开始识别，也可以将 PDF 或图片拖入这里。';$('#empty-action').dataset.action=rows.length?'reset-filter':'scan';$('#empty-action').innerHTML=rows.length?'清除筛选':`${icon('scan')}开始识别`;
 $('#range').textContent=visible.length?`显示 ${(page-1)*pageSize+1}–${Math.min(page*pageSize,visible.length)} 条，共 ${visible.length} 条`:'共 0 条记录';$('#page-indicator').textContent=`${page} / ${pages}`;$('#previous').disabled=page<=1;$('#next').disabled=page>=pages;$('#export').disabled=!rows.length||scanning;$('#cleanup-trigger').disabled=scanning;$('#scan').innerHTML=icon(scanning?'close':'scan')+`<span>${scanning?'取消识别':'开始识别'}</span>`;$('#scan').title=scanning?'取消识别并保留已完成的结果':'';
 document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.setAttribute('aria-pressed',b.dataset.filter===filter)});
 $('#filter-note').hidden=filter!=='attention'&&filter!=='duplicate';$('#filter-note').textContent=filter==='attention'?'需关注记录可能同时属于重复单号；截图留存不会消除识别异常。':'相同单号置顶显示，去重后总价仅采用一份规范记录；需关注状态仍单独保留。';
 $('#batch-time').textContent=scanning?'识别进行中':rows.length?'本批识别完成':'等待导入关单';
}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500)}
function closeMenu(){$('#cleanup-menu').hidden=true;$('#cleanup-trigger').setAttribute('aria-expanded','false')}
function openDialog(content){if(!$('#dialog').open)lastFocus=document.activeElement;$('#dialog-content').innerHTML=content;icons($('#dialog'));if(!$('#dialog').open)$('#dialog').showModal();closeMenu()}
function dialogTop(title){return `<div class="dialog-top"><h2 id="dialog-title">${title}</h2><button class="close-button" data-action="close" aria-label="关闭弹窗">${icon('close')}</button></div>`}
function closeDialog(){clearTimeout(verifyTimeout);$('#dialog').close();lastFocus?.focus()}
function settings(){openDialog(`${dialogTop('工作目录设置')}<div class="dialog-body"><p class="dialog-sub">为关单识别和核验截图指定独立的工作位置。</p><label class="field">关单读取目录<input id="source-input" value="${esc($('#source-path').textContent)}"><small>仅扫描当前层的 PDF 与图片，不扫描子文件夹。</small></label><label class="field">核验截图保存目录<input id="capture-input" value="${esc($('#capture-path').textContent)}"><small>截图以报关单号命名，同名文件保留为新副本。</small></label><p id="settings-error" class="dialog-error" hidden>请输入两个工作目录。</p><div class="notice">${icon('folder')}<span>此处为界面提案，路径仅在预览中更新；桌面版通过 Windows 文件夹选择器设置目录。</span></div></div><div class="dialog-footer"><button class="button" data-action="close">取消</button><button class="button primary" data-action="save-settings">保存设置</button></div>`)}
function verification(r,mode='waiting'){
 verificationRow=r;
 const timed=mode==='timeout',saved=mode==='saved';
 openDialog(`${dialogTop(saved?'核验截图已留存':'在线核验')}<div class="dialog-body"><p class="dialog-sub">中国国际贸易单一窗口 · 人工查询，自动留存</p><div class="verification-id"><span>报关单号</span><strong>${r.no}</strong></div><ol class="steps"><li class="done"><span class="step-icon">${icon('check')}</span><div><strong>打开查询页面，填入报关单号</strong><p>使用支持自动填写的默认浏览器，必要时自动使用 Edge / Chrome。</p></div></li><li class="${saved?'done':'current'}"><span class="step-icon">${saved?icon('check'):'2'}</span><div><strong>${saved?'人工查询已完成':'请在浏览器输入验证码并点击查询'}</strong><p>验证码由你完成；检测到稳定结果后，程序将自动保存长截图。</p></div></li><li class="${saved?'done':'waiting'}"><span class="step-icon">${saved?icon('check'):'3'}</span><div><strong>${saved?'长截图已保存':'等待结果，自动保存长截图'}</strong><p>${saved?`${r.no}.png`:'保存后在列表标记“已留存”，识别异常提示继续保留。'}</p></div></li></ol>${timed?`<div class="notice warning">${icon('clock')}<span>90 秒内未能自动确认结果。请先检查网页是否显示本单结果，再点击“立即截图”。</span></div>`:''}${!saved?'<button class="dialog-demo" data-action="simulate-result">预览：模拟检测到结果</button> <button class="dialog-demo" data-action="simulate-timeout">预览：模拟 90 秒超时</button>':''}</div><div class="dialog-footer"><span class="capture-footer-note">${saved?'截图留存不代表海关放行。':timed?'确认网页内容后可手动留存。':'等待期间可关闭此窗口。'}</span><button class="button" data-action="close">${saved?'完成':'关闭'}</button>${saved?'':`<button class="button primary" data-action="capture" ${timed?'':'disabled'}>${icon('image')}立即截图</button>`}</div>`);
 clearTimeout(verifyTimeout);if(mode==='waiting')verifyTimeout=setTimeout(()=>{if($('#dialog').open)verification(r,'timeout')},90000);
}
function cleanup(type,step=1){cleanupType=type;cleanupStep=step;const list=type==='list',captures=type==='captures',count=list?rows.length:captures?new Set(rows.filter(r=>r.saved).map(r=>r.no)).size:20;
 const title=list?'清理当前列表？':step===1?(captures?'清理核验截图？':'清理关单源文件？'):'再次确认移入回收站';
 openDialog(`${dialogTop(title)}<div class="dialog-body"><p class="dialog-sub">${list?'列表清理仅移除当前批次记录，源文件与核验截图均保留。':'请核对文件范围。只处理当前目录，不进入子文件夹。'}</p><div class="cleanup-list"><div><span>操作对象</span><strong>${list?'本批全部记录':captures?'核验截图 PNG':'PDF / 图片源文件'}</strong></div><div><span>${list?'记录数量':'待处理数量'}</span><strong>${count} ${list?'条':'份'}${list?'':'（示例）'}</strong></div>${list?'':`<div><span>目标目录</span><strong>${esc($(captures?'#capture-path':'#source-path').textContent)}</strong></div><div><span>处理方式</span><strong>移入 Windows 回收站</strong></div>`}</div><div class="notice ${list?'warning':'danger'}">${icon(list?'help':'warning')}<span>${list?'关单文件、已保存截图和工作目录不会改变。':'所列文件将从当前目录移走。确认前请核对目录与数量；被占用的文件将保留并报告。'}</span></div>${step===2?'<label class="check-confirm"><input type="checkbox" id="confirm-cleanup">我已核对目录和文件数量，确认移入回收站。</label>':''}</div><div class="dialog-footer"><button class="button" data-action="close" autofocus>取消</button><button id="confirm-cleanup-button" class="button danger" data-action="confirm-cleanup" ${step===2?'disabled':''}>${list?'清理列表':step===1?'继续确认':'移入回收站'}</button></div>`)
}
function startScan(frozen=false){if(scanning)return cancelScan();scanning=true;closeMenu();rows=structuredClone(demoRows.slice(0,frozen?8:0));filter='all';$('#search').value='';$('#progress').hidden=false;setProgress(rows.length);render();if(!frozen){scanTimer=setInterval(()=>{if(rows.length<20){rows.push(structuredClone(demoRows[rows.length]));setProgress(rows.length);render()}else{scanning=false;clearInterval(scanTimer);$('#progress').hidden=true;render();toast('演示识别完成：20 份文件，2 组重复单号。')}},450)}}
function setProgress(n){$('#progress-text').textContent=`正在识别 ${n} / 20`;$('#progress-file').textContent=demoRows[Math.min(n,19)].source;$('#progress-fill').style.width=`${n*5}%`}
function cancelScan(){clearInterval(scanTimer);scanning=false;$('#progress').hidden=true;render();toast(`识别已取消，保留已完成的 ${rows.length} 条结果（演示）。`)}
function reset(empty=false){clearInterval(scanTimer);scanning=false;$('#progress').hidden=true;rows=empty?[]:structuredClone(demoRows);filter='all';page=1;$('#search').value='';$('#toast').hidden=true;closeMenu();render()}
function exportRows(){let content='# 关单列表导出（界面提案示例数据）\n\n';content+=`本批共 ${rows.length} 份文件，包含所有分页、筛选隐藏记录和重复文件。\n\n`;content+='此演示仅导出界面字段；正式版仍使用现有 MarkdownListExporter 输出完整分项价格与复核金额。\n\n';rows.forEach((r,i)=>{content+=`## 关单 ${i+1}\n\n- 报关单号：${r.no}\n- 境外收货人：${r.company}\n- 合同协议号：${r.contract}\n- 已确认货值：${r.currency} ${num(r.amount)}\n- 识别状态：${r.attention?'需关注；金额仅含已确认部分':r.duplicate?'重复单号':'识别完成'}\n\n---\n\n`});const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='关单列表_界面提案示例.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`已导出本批全部 ${rows.length} 份示例记录。`)}
const actions={
'settings':settings,'save-settings':()=>{const a=$('#source-input').value.trim(),b=$('#capture-input').value.trim();if(!a||!b){$('#settings-error').hidden=false;return}$('#source-path').textContent=a;$('#source-path').title=a;$('#capture-path').textContent=b;$('#capture-path').title=b;closeDialog();toast('预览中的目录设置已更新。')},
'close':closeDialog,'export':exportRows,'scan':()=>startScan(),'cancel-scan':cancelScan,
'cleanup-menu':()=>{$('#cleanup-menu').hidden=!$('#cleanup-menu').hidden;$('#cleanup-trigger').setAttribute('aria-expanded',!$('#cleanup-menu').hidden)},
'clear-list':()=>cleanup('list'),'clear-files':()=>cleanup('files'),'clear-captures':()=>cleanup('captures'),
'confirm-cleanup':()=>{if(cleanupType!=='list'&&cleanupStep===1){cleanup(cleanupType,2);return}if(cleanupType==='list'){rows=[];render();closeDialog();toast('示例列表已清空，源文件与截图均未操作。')}else{closeDialog();toast('清理流程演示完成。没有对任何真实文件执行操作。')}},
'duplicates':()=>{filter='duplicate';page=1;render()},'reset-filter':()=>{filter='all';$('#search').value='';render()},
'previous':()=>{page--;render();$('#table-viewport').scrollTop=0},'next':()=>{page++;render();$('#table-viewport').scrollTop=0},
'verify':el=>verification(rows.find(r=>r.id===Number(el.dataset.id))),
'simulate-timeout':()=>verification(verificationRow,'timeout'),
'simulate-result':()=>{rows.filter(r=>r.no===verificationRow.no).forEach(r=>r.saved=true);render();verification(verificationRow,'saved')},
'capture':()=>{rows.filter(r=>r.no===verificationRow.no).forEach(r=>r.saved=true);render();closeDialog();toast('示例截图已留存；识别异常状态继续保留。')},
'demo-main':()=>reset(),'demo-empty':()=>reset(true),'demo-scan':()=>{reset();startScan(true)},'demo-verify':()=>verification(rows[2]||demoRows[2]),
'help':()=>openDialog(`${dialogTop('使用说明')}<div class="dialog-body"><p class="dialog-sub">本页面为可交互界面提案，展示的关单均为示例数据。</p><ol class="help-list"><li>设置关单与截图目录，点击开始识别。</li><li>先处理重复与需关注记录，按币种查看合计。</li><li>列表导出包含全部记录，分项核对使用导出文档。</li><li>逐单打开网站，输入验证码后查询并保存截图。</li><li>清理菜单分别管理列表、源文件和截图。</li></ol></div><div class="dialog-footer"><button class="button primary" data-action="close">知道了</button></div>`)
};
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action&&!action.disabled){actions[action.dataset.action]?.(action);return}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;page=1;render();return}if(!e.target.closest('.menu-host'))closeMenu();const cell=e.target.closest('tbody td[tabindex]');if(cell){if(!e.ctrlKey&&!e.metaKey)selected.clear();if(selected.has(cell))selected.delete(cell);else selected.add(cell);document.querySelectorAll('td.selected').forEach(c=>c.classList.remove('selected'));selected.forEach(c=>c.classList.add('selected'));$('#selection-hint').textContent=`已选中 ${selected.size} 个单元格 · Ctrl+C 复制`}});
document.addEventListener('change',e=>{if(e.target.id==='confirm-cleanup')$('#confirm-cleanup-button').disabled=!e.target.checked});
$('#search').addEventListener('input',()=>{page=1;render()});$('#page-size').addEventListener('change',e=>{pageSize=Number(e.target.value);page=1;render()});
document.addEventListener('keydown',async e=>{if(e.key==='Escape')closeMenu();if((e.key==='Enter'||e.key===' ')&&e.target.matches('td[tabindex]')){e.preventDefault();e.target.click();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'&&selected.size&&document.activeElement.tagName!=='INPUT'){e.preventDefault();const groups=new Map();[...selected].sort((a,b)=>a.parentElement.rowIndex-b.parentElement.rowIndex||a.cellIndex-b.cellIndex).forEach(c=>{const row=c.parentElement.rowIndex;if(!groups.has(row))groups.set(row,[]);groups.get(row).push(c.innerText.replace(/\n/g,' '))});try{await navigator.clipboard.writeText([...groups.values()].map(a=>a.join('\t')).join('\n'));toast(`已复制 ${selected.size} 个单元格。`)}catch{toast('浏览器未允许剪贴板访问，请直接选择文字后复制。')}}});
$('#rows').addEventListener('dblclick',e=>{if(e.target.closest('button'))return;if(e.target.closest('tr'))toast('桌面版将在默认应用中打开该源文件；此处为示例。')});
$('#table-viewport').addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.classList.add('drag-over')});$('#table-viewport').addEventListener('dragleave',e=>e.currentTarget.classList.remove('drag-over'));$('#table-viewport').addEventListener('drop',e=>{e.preventDefault();e.currentTarget.classList.remove('drag-over');toast('这是界面提案，未读取拖入文件。请在桌面程序中使用真实识别。')});
icons();render();window.prototype={reset,verification,cleanup,startScan,render,getRows:()=>rows};
